name: CI (Build & Test)

on:
  push:
    branches:
      - main

  pull_request:
    branches-ignore:
      - "changeset-release/main"

    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    if: ${{ github.ref != 'refs/heads/changeset-release/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Remove yarnrc
        run: rm .yarnrc.yml

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Setup yarn version
        run: yarn set version berry

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Type check
        run: yarn tc

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
