name: CI (Build & Test)

on:
  push:
    branches:
      - main

  pull_request:
    branches-ignore:
      - "changeset-release/main"

    types:
      - opened
      - synchronize

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-latest]


    name: Build and Test
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref != 'refs/heads/changeset-release/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn workspace @carbonteq/nodebus-core add -P @carbonteq/hexapp

      - name: Build
        run: yarn build

      - name: Type check
        run: yarn tc

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
